### ISSUE TITLE
pdf and excel generation based on facelet tags

### ISSUE THREAD

**Issue by omidp** [omnifaces/oyena#24]
Hi, 

This project seems promising. It might be a good idea to be able to generate PDF and excel based on facelet tags.

There is an example in [Seam documentation](http://docs.jboss.org/seam/2.2.2.Final/reference/en-US/html_single/#itext.list) to get the idea.

**Comment by manorrock** [comment]
Closing as we created 3 separate issues to track this work, see issues #25, #26  and #27. If you think I missed something feel free to comment on this issue. Thanks!
